export const ADD_CAR_TO_COMPARE = 'ADD_CAR_TO_COMPARE';
export const REMOVE_CAR_FROM_COMPARE = 'REMOVE_CAR_FROM_COMPARE';
export const FETCH_CARS_REQUEST = 'FETCH_CARS_REQUEST';
export const FETCH_CARS_SUCCESS = 'FETCH_CARS_SUCCESS';
export const FETCH_CARS_FAILURE = 'FETCH_CARS_FAILURE';
